language: cpp
sudo: false

matrix:
  include:
    - os: linux
      env: COMPILER=g++-5 BUILD_TYPE=Debug
      addons:
        apt:
          sources: [kubuntu-backports, ubuntu-toolchain-r-test, george-edison55-precise-backports]
          packages: [cmake, g++-5]
    # python
    - os: linux
      env: COMPILER=g++-5 BUILD_TYPE=Debug CMAKE_EXTRA_ARGS="-Dmwe_WITH_PYTHON=ON"
      sudo: true
      addons:
        apt:
          sources: [kubuntu-backports, ubuntu-toolchain-r-test, george-edison55-precise-backports, deadsnakes]
          packages: [cmake, g++-5, python3.5-dev]
      install: pip install numpy

before_script:
  - which $COMPILER
  - mkdir build && cd build
  - cmake ${CMAKE_EXTRA_ARGS} .. -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cmake --build .
  
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/Library/Caches/pip

script:
  - ctest . -VV -C Debug

branches:
  only:
    - master
    - dev

notifications:
  email: false
