language: cpp
sudo: false

env:
  global:
    - COMPILER=g++-5
    - BUILD_TYPE=Debug

matrix:
  include:
    # -- core library tests
    - os: osx
      osx_image: xcode7.3
      env: COMPILER=clang++

    - os: linux
      addons:
        apt:
          sources: [kubuntu-backports, ubuntu-toolchain-r-test, george-edison55-precise-backports]
          packages: [cmake, g++-5]
    
    # -- python
    - os: osx
      osx_image: xcode7.3
      env: CMAKE_EXTRA_ARGS="-Dmwe_WITH_PYTHON=ON" COMPILER=clang++ 
      install:
        - pyenv install 3.5.0
        - pyenv global 3.5.0
        - pip install --user --upgrade pip
        - pip install --user numpy

    - os: linux
      env: CMAKE_EXTRA_ARGS="-Dmwe_WITH_PYTHON=ON"
      addons:
        apt:
          sources: [kubuntu-backports, ubuntu-toolchain-r-test, george-edison55-precise-backports, deadsnakes]
          packages: [cmake, g++-5, python3.5-dev]
      install:
        - pip install --user --upgrade pip
        - pip install --user numpy
    
    # -- nodejs
    - os: linux
      dist: trusty
      env: CMAKE_EXTRA_ARGS="-Dmwe_WITH_NODEJS=ON"
      addons:
        apt:
          sources: [kubuntu-backports, ubuntu-toolchain-r-test, george-edison55-precise-backports]
          packages: [cmake, g++-5]
      install:
         - rm -rf ~/.nvm && git clone --depth 1 --branch v0.33.1 https://github.com/creationix/nvm.git ~/.nvm
         - source ~/.nvm/nvm.sh && nvm install 5
         - node --version
    
    - os: osx
      osx_image: xcode7.3
      env: CMAKE_EXTRA_ARGS="-Dmwe_WITH_NODEJS=ON" COMPILER=clang++ 
      install:
         - rm -rf ~/.nvm && git clone --depth 1 --branch v0.33.1 https://github.com/creationix/nvm.git ~/.nvm
         - source ~/.nvm/nvm.sh && nvm install 5
         - node --version
    
    # -- java (oraclejdk7)
    - os: linux
      env: CMAKE_EXTRA_ARGS="-Dmwe_WITH_JAVA=ON"
      jdk: oraclejdk7
      addons:
        apt:
          sources: [kubuntu-backports, ubuntu-toolchain-r-test, george-edison55-precise-backports]
          packages: [cmake, g++-5]
      install:
        - jdk_switcher use oraclejdk7
    
    # -- java (openjdk7)
    - os: linux
      env: CMAKE_EXTRA_ARGS="-Dmwe_WITH_JAVA=ON"
      jdk: openjdk7
      addons:
        apt:
          sources: [kubuntu-backports, ubuntu-toolchain-r-test, george-edison55-precise-backports]
          packages: [cmake, g++-5]
      install:
        - jdk_switcher use openjdk7

    

before_script:
  - which $COMPILER
  - mkdir build && cd build
  - cmake ${CMAKE_EXTRA_ARGS} .. -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cmake --build .
  
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/Library/Caches/pip

script:
  - ctest . -VV -C Debug

branches:
  only:
    - master
    - dev

notifications:
  email: false
