language: cpp
sudo: false

env:
  global:
    - BUILD_TYPE=Debug

dist: trusty
osx_image: xcode7.3

addons:
  apt:
    sources: [kubuntu-backports, ubuntu-toolchain-r-test, george-edison55-precise-backports]
    packages: [cmake, g++-5]

matrix:
  include:
    # -- core library tests
    - os: linux
    - os: osx

    # -- python
    - os: linux
      env: CMAKE_EXTRA_ARGS="-Dmwe_WITH_PYTHON=ON"
      addons:
        apt:
          sources: [kubuntu-backports, ubuntu-toolchain-r-test, george-edison55-precise-backports, deadsnakes]
          packages: [cmake, g++-5, python3.5-dev]
      install:
        - pip install --user --upgrade pip
        - pip install --user numpy

    - os: osx
      env: CMAKE_EXTRA_ARGS="-Dmwe_WITH_PYTHON=ON"
      install:
        - pyenv install 3.5.0
        - pyenv global 3.5.0
        - pip install --user --upgrade pip
        - pip install --user numpy

    # -- nodejs
    - os: linux
      env: CMAKE_EXTRA_ARGS="-Dmwe_WITH_NODEJS=ON"

      install:
         - rm -rf ~/.nvm && git clone --depth 1 --branch v0.33.1 https://github.com/creationix/nvm.git ~/.nvm
         - source ~/.nvm/nvm.sh && nvm install 5

    - os: osx
      env: CMAKE_EXTRA_ARGS="-Dmwe_WITH_NODEJS=ON"
      install:
         - rm -rf ~/.nvm && git clone --depth 1 --branch v0.33.1 https://github.com/creationix/nvm.git ~/.nvm
         - source ~/.nvm/nvm.sh && nvm install 5

    # -- java (oraclejdk7, linux)
    - os: linux
      env: CMAKE_EXTRA_ARGS="-Dmwe_WITH_JAVA=ON"
      sudo: required
      jdk: oraclejdk7
      install:
        - jdk_switcher use oraclejdk7

    # -- java (openjdk7, linux)
    - os: linux
      env: CMAKE_EXTRA_ARGS="-Dmwe_WITH_JAVA=ON"
      sudo: required
      jdk: openjdk7
      install:
        - jdk_switcher use openjdk7

    # -- java (oraclejdk8, osx)
    - os: osx
      env: CMAKE_EXTRA_ARGS="-Dmwe_WITH_JAVA=ON"
      install:
         - java -version

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then export COMPILER=clang++ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export COMPILER=g++-5   ; fi
  - mkdir build && cd build
  - cmake ${CMAKE_EXTRA_ARGS} .. -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cmake --build .

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/pip

script:
  - ctest . -VV -C Debug

branches:
  only:
    - master
    - dev

notifications:
  email: false
