version: 0.1.{build}
image:
- Visual Studio 2015
test: off
platform:
- x64
environment:
  matrix:
  - CORE: true
  - CONDA: 36
  - JAVA: 7
  - NODEJS: 5
matrix:
  fast_finish: true  # Stop remaining jobs after a job failure
install:
- ps: |
    git submodule update --init --recursive
    $env:CMAKE_GENERATOR = "Visual Studio 14 2015 Win64"
    $env:EXTRA_CMAKE_ARGS = ""
    if ($env:CONDA) {
      if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
      $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
      conda install -y -q numpy
      $env:EXTRA_CMAKE_ARGS = "-Dmwe_WITH_PYTHON=ON"
    }
    if ($env:JAVA) {
      $env:EXTRA_CMAKE_ARGS = "-Dmwe_WITH_JAVA=ON"
    }
    if ($env:NODEJS) {
      Install-Product node $env:NODEJS x64
      $env:EXTRA_CMAKE_ARGS = "-Dmwe_WITH_NODEJS=ON"
    }
build_script:
- mkdir build && cd build
- cmake -G "%CMAKE_GENERATOR%" "%EXTRA_CMAKE_ARGS%" ..
- set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmake --build . --config Debug
- ctest . -VV -C Debug
